### ISSUE TITLE
Email Newsletter not getting sent

### ISSUE THREAD

**Issue by AndrewMagliozzi** [AdmitHub/Telescope#7]
the email newsletter is set to go out on Monday at 11am, but I don't think it's getting sent.  I haven't gotten one for a while.

**Comment by yourcelf** [comment]
Can you please verify that the MailChimp API key and list ID are correct?  Next, can you log into the mailchimp account and see if there are any error notices or other details from newsletter delivery attempts?

**Comment by AndrewMagliozzi** [comment]
Yikes. I'm on the way to the airport now. I haven't changed the API keys. Can't see the logs at the moment or for a couple days here.

**Comment by yourcelf** [comment]
My findings so far: no newsletter has gone out since we upgraded to Telescope v0.24.0.  Newsletters should be scheduled via SyncedCron, but the `cronHistory` collection doesn't have any entries related to newsletters.  `telescope-newsletter` defines a `Campaigns` collection, but this appears to not actually be used anymore, and the collection is empty.  Posts do get a `scheduledAt` field set to them if they are included in a newsletter; but nothing has had that set since the upgrade.

Telescope has a [troubleshooting method](https://telescope.readme.io/docs/sending-newsletters#troubleshooting) which can be called by the browser console (if you're logged in) to create a test mailing.  This creates an _actual campaign_ in MailChimp, but doesn't mark the posts as sent: `Meteor.call('testCampaign')`.  Calling this works correctly to create a campaign in MailChimp.

Telescope has a method to log details about the next scheduled newsletter from SyncedCron: `Meteor.call('getNextJob')`, which logs the next scheduled date in the server log.  Running this shows the correct date (next Monday).

So as near as I can tell: everything looks like it should work.  It looks like there ought to have been a newsletter or two that didn't happen in the last couple of weeks, but at the moment I don't see what would've prevented them from going out.

**Comment by yourcelf** [comment]
I _think_ this is fixed now.  An incompletely applied migration left some users with empty `telescope.slug`, which was causing the rendering of the email template to fail for them.  We'll know for sure the next time a scheduled newsletter is supposed to go out.

If you like, we can reschedule one for sooner to try it out -- just let me know when you want it to happen.
